### ISSUE TITLE
multiline_block/paragraph의 정확한 블럭 영역 판정

### ISSUE THREAD

**Issue by Danue1** [Danue1/namumark#1]
전체 문서 파싱을 시도했으나 실패하고 있습니다.
일단 발견한 이유로는 multiline_block/paragraph의 블럭 영역을 제대로 인식하지 못 하는 문제가 있습니다.

# 해결해야 하는 이슈

- [ ] multiline_block/paragraph의 정확한 블럭 영역을 판정하는 함수 추가

  - [ ] blockquote의 시작 위치인지 판정하는 함수 추가
  - [ ] horizontal_rule의 시작 위치인지 판정하는 함수 추가
  - [ ] list의 시작 위치인지 판정하는 함수 추가
  - [ ] comment의 시작 위치인지 판정하는 함수 추가
  - [ ] open_heading 시작 위치인지 판정하는 함수 추가

**Comment by rkxx08** [comment]
실패하는 입력 데이터의 샘플을 어딘가에 저장해 두면 좋을것 같습니다.

**Comment by Danue1** [comment]
그렇네요. 좋은 의견 감사합니다.
통합 테스트용 문서 데이터를 추가하기 전까지는 아래의 링크에서 가져와 테스트하려고 합니다.
나무위키가 잘(?) 보존하고 있으니 링크 정도만 추가해도 괜찮겠네요.

https://namu.wiki/w/%EC%BD%9C%EB%9D%BC%EC%B8%A0%20%EC%B6%94%EC%B8%A1
